
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.csvMonsterSpawn
{

public sealed class TbMonsterSpawn
{
    private readonly Dictionary<int, csvMonsterSpawn.MonsterSpawn> _dataMap;
    private readonly List<csvMonsterSpawn.MonsterSpawn> _dataList;
    
    public TbMonsterSpawn(JSONNode _json)
    {
        _dataMap = new Dictionary<int, csvMonsterSpawn.MonsterSpawn>();
        _dataList = new List<csvMonsterSpawn.MonsterSpawn>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = csvMonsterSpawn.MonsterSpawn.DeserializeMonsterSpawn(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public Dictionary<int, csvMonsterSpawn.MonsterSpawn> DataMap => _dataMap;
    public List<csvMonsterSpawn.MonsterSpawn> DataList => _dataList;

    public csvMonsterSpawn.MonsterSpawn GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public csvMonsterSpawn.MonsterSpawn Get(int key) => _dataMap[key];
    public csvMonsterSpawn.MonsterSpawn this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
}

}