
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.csvSound
{

public sealed class Sound :  Bright.Config.BeanBase 
{
    public Sound(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["path"].IsString) { throw new SerializationException(); }  Path = _json["path"]; }
        { if(!_json["is_loop"].IsBoolean) { throw new SerializationException(); }  IsLoop = _json["is_loop"]; }
        { if(!_json["spatical_blend"].IsNumber) { throw new SerializationException(); }  SpaticalBlend = _json["spatical_blend"]; }
    }

    public Sound(int id, string path, bool is_loop, float spatical_blend ) 
    {
        this.Id = id;
        this.Path = path;
        this.IsLoop = is_loop;
        this.SpaticalBlend = spatical_blend;
    }

    public static Sound DeserializeSound(JSONNode _json)
    {
        return new csvSound.Sound(_json);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 音频路径
    /// </summary>
    public string Path { get; private set; }
    /// <summary>
    /// 是否循环
    /// </summary>
    public bool IsLoop { get; private set; }
    /// <summary>
    /// 空间混合
    /// </summary>
    public float SpaticalBlend { get; private set; }

    public const int __ID__ = -1631777430;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Path:" + Path + ","
        + "IsLoop:" + IsLoop + ","
        + "SpaticalBlend:" + SpaticalBlend + ","
        + "}";
    }
    }
}
