
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.csvSound
{

public sealed class TbSound
{
    private readonly Dictionary<int, csvSound.Sound> _dataMap;
    private readonly List<csvSound.Sound> _dataList;
    
    public TbSound(JSONNode _json)
    {
        _dataMap = new Dictionary<int, csvSound.Sound>();
        _dataList = new List<csvSound.Sound>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = csvSound.Sound.DeserializeSound(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public Dictionary<int, csvSound.Sound> DataMap => _dataMap;
    public List<csvSound.Sound> DataList => _dataList;

    public csvSound.Sound GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public csvSound.Sound Get(int key) => _dataMap[key];
    public csvSound.Sound this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
}

}