
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.csvStage
{

public sealed class TbStage
{
    private readonly Dictionary<int, csvStage.Stage> _dataMap;
    private readonly List<csvStage.Stage> _dataList;
    
    public TbStage(JSONNode _json)
    {
        _dataMap = new Dictionary<int, csvStage.Stage>();
        _dataList = new List<csvStage.Stage>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = csvStage.Stage.DeserializeStage(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public Dictionary<int, csvStage.Stage> DataMap => _dataMap;
    public List<csvStage.Stage> DataList => _dataList;

    public csvStage.Stage GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public csvStage.Stage Get(int key) => _dataMap[key];
    public csvStage.Stage this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
}

}