
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.csvIcon
{

public sealed class Icon :  Bright.Config.BeanBase 
{
    public Icon(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["atlasName"].IsString) { throw new SerializationException(); }  AtlasName = _json["atlasName"]; }
        { if(!_json["iconName"].IsString) { throw new SerializationException(); }  IconName = _json["iconName"]; }
    }

    public Icon(int id, string atlasName, string iconName ) 
    {
        this.Id = id;
        this.AtlasName = atlasName;
        this.IconName = iconName;
    }

    public static Icon DeserializeIcon(JSONNode _json)
    {
        return new csvIcon.Icon(_json);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 图集名称
    /// </summary>
    public string AtlasName { get; private set; }
    /// <summary>
    /// 图片名称
    /// </summary>
    public string IconName { get; private set; }

    public const int __ID__ = -1743448696;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AtlasName:" + AtlasName + ","
        + "IconName:" + IconName + ","
        + "}";
    }
    }
}
