
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.csvIcon
{

public sealed class TbIcon
{
    private readonly Dictionary<int, csvIcon.Icon> _dataMap;
    private readonly List<csvIcon.Icon> _dataList;
    
    public TbIcon(JSONNode _json)
    {
        _dataMap = new Dictionary<int, csvIcon.Icon>();
        _dataList = new List<csvIcon.Icon>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = csvIcon.Icon.DeserializeIcon(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public Dictionary<int, csvIcon.Icon> DataMap => _dataMap;
    public List<csvIcon.Icon> DataList => _dataList;

    public csvIcon.Icon GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public csvIcon.Icon Get(int key) => _dataMap[key];
    public csvIcon.Icon this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
}

}