
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.csvParam
{

public sealed class Param :  Bright.Config.BeanBase 
{
    public Param(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["str_value"].IsString) { throw new SerializationException(); }  StrValue = _json["str_value"]; }
    }

    public Param(int id, string str_value ) 
    {
        this.Id = id;
        this.StrValue = str_value;
    }

    public static Param DeserializeParam(JSONNode _json)
    {
        return new csvParam.Param(_json);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 配置内容
    /// </summary>
    public string StrValue { get; private set; }

    public const int __ID__ = 1555404262;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "StrValue:" + StrValue + ","
        + "}";
    }
    }
}
