
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.csvParam
{

public sealed class TbParam
{
    private readonly Dictionary<int, csvParam.Param> _dataMap;
    private readonly List<csvParam.Param> _dataList;
    
    public TbParam(JSONNode _json)
    {
        _dataMap = new Dictionary<int, csvParam.Param>();
        _dataList = new List<csvParam.Param>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = csvParam.Param.DeserializeParam(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public Dictionary<int, csvParam.Param> DataMap => _dataMap;
    public List<csvParam.Param> DataList => _dataList;

    public csvParam.Param GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public csvParam.Param Get(int key) => _dataMap[key];
    public csvParam.Param this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
}

}